sudo: false

language: node_js

node_js:
  - "12"

cache:
  yarn: true
  directories:
    - node_modules
    - .jest/cache

install:
  - yarn install

before_script:
  - yarn danger ci

script:
   - jest --runInBand --silent

notifications:
  slack: aretecode:iup7yYHuehxb7jdj20BjpimH
